export const defaultAdminConfig = {
  sections: [
    {
      id: 1,
      title: 'Hero et message principal',
      type: 'Hero',
      visible: true,
      blocks: ['Titre principal', 'Texte descriptif', 'Boutons CTA', 'Visuel TechAgency'],
    },
    {
      id: 2,
      title: 'Modeles de sites interactifs',
      type: 'Modeles',
      visible: true,
      blocks: ['Demo Psy', 'Demo Coach', 'Demo Medecin', 'Scroll simulation'],
    },
    {
      id: 3,
      title: 'Services et solutions',
      type: 'Cards',
      visible: true,
      blocks: ['Applications web', 'Mobile', 'IA', 'Cloud & DevOps'],
    },
    {
      id: 4,
      title: 'Portfolio et projets',
      type: 'Portfolio',
      visible: true,
      blocks: ['Projet 1', 'Projet 2', 'Projet 3'],
    },
    {
      id: 5,
      title: 'Temoignages et offres',
      type: 'Conversion',
      visible: true,
      blocks: ['Temoignages', 'Pack Digital', 'Pack Business System'],
    },
  ],
  offers: [
    { id: 1, name: 'Pack Digital', price: 'Sur devis', status: 'Actif' },
    { id: 2, name: 'Pack Business System', price: 'Sur devis', status: 'Populaire' },
    { id: 3, name: 'Pack Sur Mesure', price: 'Audit gratuit', status: 'Actif' },
  ],
  projects: [
    {
      id: 1,
      title: 'Site vitrine Gym Ten Chi',
      description: 'Site moderne pour une salle de sport avec presentation des offres et parcours de conversion.',
      image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80',
      technologies: 'React, Vercel, Responsive',
      url: 'https://gym-ten-chi.vercel.app/',
      visible: true,
    },
  ],
  settings: {
    agencyName: 'TechAgency',
    tagline: 'Software & AI Studio',
    email: 'contact@techagency.ma',
    phone: '+212 6 00 00 00 00',
    address: 'Casablanca, Maroc',
    domain: 'techagency.ma',
    primaryColor: '#081A33',
    accentColor: '#25D7D7',
    maintenance: false,
    notifications: true,
    backups: true,
    adminProtection: true,
  },
};
